# Generated by Django 4.2.4 on 2024-02-04 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
